---
name: 'Set up Aerospike Database'
description: 'Aerospike – the reliable, high performance, distributed database optimized for flash and RAM.'
author: 'step-security'
branding:
  icon: 'database'
  color: 'red'
inputs:
  port:
    description: 'Aerospike port'
    required: false
    default: '3000'
  server-version:
    description: 'Aerospike server version'
    required: false
    default: 'latest'
  config-file:
    description: 'Aerospike configuration file'
    required: false
    default: ''
  feature-key-file:
    description: 'Aerospike EE feature key file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/github-action-aerospike:v1.1.1@sha256:4ba00f7bb6def640618d47ed7adbcf7fe9d3623f9ddc51f0cd8f99e6534dca01' #v1.1.1
  args:
    - ${{ inputs.port }}
    - ${{ inputs.server-version }}
    - ${{ inputs.config-file }}
    - ${{ inputs.feature-key-file }}
