---
name: 'Set up Aerospike Database'
description: 'Aerospike – the reliable, high performance, distributed database optimized for flash and RAM.'
author: 'step-security'
branding:
  icon: 'database'
  color: 'red'
inputs:
  port:
    description: 'Aerospike port'
    required: false
    default: '3000'
  server-version:
    description: 'Aerospike server version'
    required: false
    default: 'latest'
  config-file:
    description: 'Aerospike configuration file'
    required: false
    default: ''
  feature-key-file:
    description: 'Aerospike EE feature key file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/github-action-aerospike:v1.1.0@sha256:ed8cedf97dfe58cb6721158f7bdac0a1fbf9c8a9d4576bfc559ebe88d1fcacdb' #v1.1.0
  args:
    - ${{ inputs.port }}
    - ${{ inputs.server-version }}
    - ${{ inputs.config-file }}
    - ${{ inputs.feature-key-file }}
