---
name: 'Set up Aerospike Database'
description: 'Aerospike – the reliable, high performance, distributed database optimized for flash and RAM.'
author: 'step-security'
branding:
  icon: 'database'
  color: 'red'
inputs:
  port:
    description: 'Aerospike port'
    required: false
    default: '3000'
  server-version:
    description: 'Aerospike server version'
    required: false
    default: 'latest'
  config-file:
    description: 'Aerospike configuration file'
    required: false
    default: ''
  feature-key-file:
    description: 'Aerospike EE feature key file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/github-action-aerospike:v1.1.2@sha256:50c047a34f5e9e89904b81edf0e4aa149e7c3f32200486721f833c2df027aaa0' #v1.1.2
  args:
    - ${{ inputs.port }}
    - ${{ inputs.server-version }}
    - ${{ inputs.config-file }}
    - ${{ inputs.feature-key-file }}
